### ISSUE TITLE
JSON bodies missing keys return content-type: text/plain

### ISSUE THREAD

**Issue by maxcountryman** [rusty-crab/warp-api-starter-template#16]
For requests containing a JSON body that are e.g. missing keys, the server will respond with a non-JSON formatted response. It seems it would probably be more desirable to response with a properly formatted JSON error.

**Comment by aslamplr** [comment]
Thank you @maxcountryman for creating this issue. If you could verify this is fixed that would be great. Otherwise please re-open this issue.

**Comment by maxcountryman** [comment]
@aslamplr yep, this seems to work much better.

**Comment by maxcountryman** [comment]
It does seem like missing routes (i.e. what should be a 404) are now returning 500s however.

**Comment by aslamplr** [comment]
> It does seem like missing routes (i.e. what should be a 404) are now returning 500s however.

@maxcountryman thank you for reporting this issue. I have opened a new issue to track this #20 
I would probably able to work on this over the weekend

**Comment by aslamplr** [comment]
> > It does seem like missing routes (i.e. what should be a 404) are now returning 500s however.
> 
> @maxcountryman thank you for reporting this issue. I have opened a new issue to track this #20
> I would probably able to work on this over the weekend

#20 is fixed now
