### ISSUE TITLE
It does seem like missing routes (i.e. what should be a 404) are now returning 500

### ISSUE THREAD

**Issue by aslamplr** [rusty-crab/warp-api-starter-template#20]
It does seem like missing routes (i.e. what should be a 404) are now returning 500s however.

_Originally posted by @maxcountryman in https://github.com/rusty-crab/warp-api-starter-template/issues/16#issuecomment-666387858_

**Comment by aslamplr** [comment]
Seems like `warp` rejects with `405` for unknown paths. 

![Screenshot 2020-08-01 at 3 17 31 AM](https://user-images.githubusercontent.com/7376908/89080643-0da2e580-d3a7-11ea-8107-8f4e730c21e3.png)

**Comment by maxcountryman** [comment]
That doesn't seem right. 405 should be returned when a route is found but the wrong request method was used. I'm also seeing something different where e.g. cURLing localhost:8000/404 is resulting in a 500, as before.

```
$ curl localhost:8000/404 -s | jq .
{
  "type": "https://httpstatuses.com/500",
  "status": 500,
  "title": "Internal Server Error"
}
```

**Comment by aslamplr** [comment]
@maxcountryman I am unable to reproduce the above issue in `master`. I assume you are running the warp server to listen to on port `8000`.
Mine is listening on port `3535` and the response looks the following for `curl localhost:3535/404`. 

![Screenshot 2020-08-01 at 10 49 54 PM](https://user-images.githubusercontent.com/7376908/89106732-01239900-d44a-11ea-85db-5da74823c5c8.png)

Could you please provide some context to let me reproduce the issue. Thank you.

**Comment by maxcountryman** [comment]
Setting aside the persistent 500, a 405 is an incorrect response in your example, assuming that path doesn't exist.

**Comment by aslamplr** [comment]
> Setting aside the persistent 500, a 405 is an incorrect response in your example, assuming that path doesn't exist.

Agree with you on this. And your assumption is correct, the path doesn't exist.

The behavior is coming from warp itself, it seems (Edit: This is only my intuition and not conclusive with evidence). I haven't checked if this issue is reported in warp's repo. 

I am re-opening the issue to further investigate this.

Edit: Also, if the usage and combination of warp filters causing this.

**Comment by aslamplr** [comment]
@maxcountryman Please add if you think there is a better approach to narrow down this. Thank you again.

**Comment by maxcountryman** [comment]
> > Setting aside the persistent 500, a 405 is an incorrect response in your example, assuming that path doesn't exist.
> 
> Agree with you on this. And your assumption is correct, the path doesn't exist.
> 
> The behaviour is coming from warp itself, it seems. I haven't checked if this issue is reported in warp's repo. 
> 
> I am re-opening the issue to further investigate this.
> 
> Edit: Also, if the usage and combination of warp filters causing this. 

I'm curious what you mean when you say warp is causing this?

Are you able to reproduce this with a different warp application?

I'd try to distill this to a simpler example to narrow things down.

**Comment by aslamplr** [comment]
> I'm curious what you mean when you say warp is causing this?

I am not conclusive about this, I will edit my statement above not to reflect that. It is just that it is my intuition.

> Are you able to reproduce this with a different warp application?

No, that will be my next step anyway.

> I'd try to distill this to a simpler example to narrow things down.

I really appreciate it if you could do it and add clarity to the scope of the issue.

**Comment by aslamplr** [comment]
Pasting this here for reference https://github.com/seanmonstar/warp/issues/77

**Comment by aslamplr** [comment]
I am able to narrow down the issue. This issue is caused by the way in which `warp` filters are used or how it works.
Current usage across the codebase, the HTTP method filter comes before the path filter.

Example:
```rust
// Existense of these kind of route would cause the 405 behaviour!!
let auth = warp::post()
    .and(warp::path("auth"))
    .map(|| format!("This single route alone, cause a 405 for any missing routes!!"));
```

It should be re-written to have the path filter come first to have a proper 404 behaviour!
```rust
let auth = warp::path("auth")  
    .and(warp::post())  
    .map(|| format!("I am well scoped route, which only accepts a post!"));
```
